# Generated by Django 2.2.5 on 2019-09-27 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='modificado em')),
                ('titulo', models.CharField(blank=True, max_length=3, verbose_name='Treino')),
            ],
            options={
                'db_table': 'treino',
            },
        ),
        migrations.AlterField(
            model_name='fichaexercicio',
            name='ficha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ficha.Ficha'),
        ),
        migrations.CreateModel(
            name='FichaAtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='modificado em')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.Ficha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ficha_atual',
            },
        ),
    ]
