# Generated by Django 2.2.5 on 2019-09-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_auto_20190924_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='exercicio',
        ),
    ]
