# Generated by Django 2.2.5 on 2019-09-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0002_auto_20190924_1404'),
        ('ficha', '0003_remove_ficha_exercicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaExercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
                ('modificado', models.DateTimeField(auto_now=True, null=True, verbose_name='modificado em')),
                ('exercicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercicio.Exercicio')),
                ('ficha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ficha.Ficha')),
            ],
            options={
                'db_table': 'ficha_exercicio',
            },
        ),
    ]
