# Generated by Django 2.2.5 on 2019-09-25 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('aplicacao', models.SmallIntegerField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_token_api', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_token',
            },
        ),
    ]
