# Generated by Django 2.2.5 on 2019-12-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_token',
            },
        ),
    ]
