# Generated by Django 2.2.5 on 2019-09-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
