# Generated by Django 2.2.5 on 2019-09-27 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0002_auto_20190927_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaexercicio',
            name='treino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ficha.Treino'),
        ),
    ]
