# Generated by Django 2.2.5 on 2019-09-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='exercicio',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='modificado',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='modificado em'),
        ),
    ]
